### ISSUE TITLE
lqrrt paper

### ISSUE THREAD

**Issue by tcjcxy30** [jnez71/lqRRT#13]
Hello Jason Nezvadovitz:
     You project is awesome, and can you tell me which papers or algorithm you used in this project?
      LQR-RRTstar?

**Comment by jnez71** [comment]
@CxyCH 
It has the functionality to work almost as what [the LQR-RRTstar paper](http://people.csail.mit.edu/tlp/pdf/2012/ICRA12_1657_FI.pdf) describes, just without the "star" part (that is, without the "rewire" step). I used to have the rewire step too but it slowed down tree growth so much (Python isn't too fast...) that I decided to abandon that step for my real-time applications. You'll notice that one of the open Issues here is to re-implement "star" (rewiring) in an effective way. Unfortunately, I probably won't get around to that as I am caught up with other work. Thanks for checking this out though! You may also notice that many of my demos use a constant cost-to-go matrix for LQRSteer, which effectively reduces them to using the most basic form of kinodynamic RRT. Again, the reason for this was because solving a Riccati equation every iteration was too slow for my applications.
